### ISSUE TITLE
Add support for arm64 simulators

### ISSUE THREAD

**Issue by dtaylor1701** [pendo-io/pendo-mobile-ios#1]
At the moment there is no binary for arm64 simulators included with the XCFramework. This means an app with Pendo as a dependency cannot be built on an Apple Silicon Mac without translation.

**Comment by MikePendo** [comment]
Hi @dtaylor1701 
The support for M1 apple silicon is available since sdk 2.11.3. for the cocoapods.
Its also available for the XCframework.
In case you still want to use the old Fat framework your can use:
`PendoLegacy ` as your pod

**Comment by amrgetment** [comment]
@MikePendo  the app not building on Apple silicon Mac even in last SDK 3.2
```
Launching lib/main.dart on iPhone 15 in debug mode...
Xcode build done.                                           17.4s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'Pendo/Pendo.h' file not found
/Users/.pub-cache/hosted/pub.dev/pendo_sdk-3.2.0/ios/Classes/PendoFlutterPlugin.m:1:8
PendoFlutterPlugin.m:1

Could not build the application for the simulator.
Error launching application on iPhone 15.
```

In 
/Users/amr/.pub-cache/hosted/pub.dev/pendo_sdk-3.2.0/ios/pendo_sdk.podspec
you can see the architecture only intel x86_64

<img width="825" alt="image" src="https://github.com/pendo-io/pendo-mobile-sdk/assets/149420647/149d6139-eeaf-4412-88cf-6a24e76741be">

**Comment by amrgetment** [comment]
By they way it is a Flutter application not native

**Comment by MikePendo** [comment]
@amrgetment 
I think that the error is somewhere else. It's the same XCframework for all our platforms and the  M1 is supported. 
(We need to remove that `VALID_ARCHS` I think its deprecated any way)
maybe you can clean the caches and try once again, can you please also verify that in the iOS project you indeed see Pendo installed i.e Pendo is in your Project for some reason Xcode doesnt see.
I see some some similar error here:
 https://stackoverflow.com/questions/77219668/lexical-or-preprocessor-issue-xcode-15-flutter-flutter-h-file-not-found
 (maybe be worth to check cocoa pod version)
 BTW: 3.2 has coddlers support if you are interested (still in BETA)

**Comment by amrgetment** [comment]
cocoa pod version is the latest 1.15.0 and SDK versions
Installing Pendo (3.2.0.8353)
Installing pendo_sdk (3.2.0)
Stackoverflow not helping

**Comment by MikePendo** [comment]
@amrgetment 
1. Do you have an option to contact one of our TS and schedule a call so we could look at it together?
2. Do you see any issues when u run `flutter doctor`?
3. Where is the error coming from? I mean how do u run it `flutter run`? can you try to run it in Xcode.
4. When you are in Xcode in `PendoFlutterPlugin.m` can u jump to `#import <Pendo/Pendo.h>` file.
5. If you create an empty project and integrate pendo , will you be able to run it?
( I am on Xcode 15.2 M1, pods 1.13  just created sample project and I dont have such issue )
6. Can you share your podFile?

**Comment by amrgetment** [comment]
@MikePendo Fix, probably by 

`sudo arch -arm64 gem install ffi `

`pod install --repo-update`

**Comment by amrgetment** [comment]
@MikePendo The following code works fine
`arch -x86_64 pod install --repo-update
`but 
`arch -arm64 pod install --repo-update` or just using `pod install --repo-update` makes an empty pendo folder in cocopods cache folders which makes my error `Pendo/Pendo.h` file not found

**Comment by MikePendo** [comment]
can you create a new sample Flutter app and add Pendo? and see if Pendo is there?

**Comment by amrgetment** [comment]
it is not there in the Cocoapods cache folder even with a new Flutter project
but the following fix it without any extra effort
Step 1- run:
`pod install --repo-update`
Step 2- add to Podfile

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      ]
    end
  end
end

```
