### ISSUE TITLE
Add support for Mac Catalyst

### ISSUE THREAD

**Issue by denisq1991** [pendo-io/pendo-mobile-ios#11]
I can't run my iOS app on Catalyst with the Pendo framework in it added via SPM.

Could you please add support for Mac Catalyst?

<img width="655" alt="Screenshot 2022-06-16 at 16 05 33" src="https://user-images.githubusercontent.com/10491099/174101255-888fa5b1-7066-42ee-8843-e0bd70d02034.png">

**Comment by MikePendo** [comment]
He @denisq1991 
I have contacted our PM and currently we dont have it on pipeline. You can try to open a TS ticket to push your request  forward.
(We are intensively working on supporting SwiftUI coddles solution)
