### ISSUE TITLE
Add readable isDebugEnabled property to PendoManager

### ISSUE THREAD

**Issue by kmaschke85** [pendo-io/pendo-mobile-ios#14]
Right now there is only the method ``- (void)setDebugMode:(BOOL)isDebugEnabled`` available on ``PendoManager`` to toggle logging on or off. But I am missing a property to read the current status of Debug Mode being enabled or disabled, so that I verify the current status of that setting at runtime.
Would be nice if you could add that property in one of the next versions.

**Comment by MikePendo** [comment]
@kmaschke85 
This property is mainly used by us in case of troubleshooting. Could you please describe your usecase?

**Comment by kmaschke85** [comment]
Never mind, I thought this through again and don't really need the debug mode. Sometimes I do, because I want to understand what's happening, but that is just the case while debugging in Xcode, so that I can change code anyways.
