### ISSUE TITLE
React Native App with React Navigation in TypeScript - Building in Microsoft AppCenter is failing for iOS

### ISSUE THREAD

**Issue by shariq-muhammad** [pendo-io/pendo-mobile-ios#18]
We use Visual Studio AppCenter to build code from our repo and in the cloud. It automatically run unit tests and releases the app to testers and stores (Android, iOS).

When building the React Native app in AppCenter, it failed for iOS with many errors for Pendo.arm64.xar. I opened the issue initially at [pendo-io/RN-demo-app-React-Navigation](https://github.com/pendo-io/RN-demo-app-React-Navigation/issues/4#issue-1396202401) repo, but was advised to open it here. 

Most of the errors are similar to the below about the address of an intrinsic:

Clang: cd /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temptc3472sy
['/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-cc1', '-cc1', '-triple', 'arm64-apple-ios9.0.0', '-emit-obj', '--mrelax-relocations', '-disable-llvm-passes', '-faligned-alloc-unavailable', '-target-sdk-version=15.4', '-fvisibility-inlines-hidden-static-local-var', '-target-abi', 'darwinpcs', '-Os', '-x', 'ir', '002', '-o', '002.o']
-= Output =-
Cannot take the address of an intrinsic!
%18 = tail call i8* bitcast (i8* (i8*, i8*, ...)* @objc_msgSend to i8* (i8*, i8*))(i8 %16, i8* %17) #12 [ "clang.arc.attachedcall"(i8* (i8*)* @llvm.objc.retainAutoreleasedReturnValue) ], !dbg !53, !clang.arc.no_objc_arc_exceptions !41
Cannot take the address of an intrinsic!
...
...
...
...
...
...
...

 %37 = call %7* bitcast (i8* (i8*, i8*, ...)* @objc_msgSend to %7* (i8*, i8*)*)(i8* %35, i8* %36) #7 [ "clang.arc.attachedcall"(i8* (i8*)* @llvm.objc.retainAutoreleasedReturnValue) ], !dbg !603
fatal error: error in backend: Broken module found, compilation aborted!
Exited with 70

Failed to compile bundle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Pendonzdrrlvp/Pendo.arm64.xar
Stderr:

/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:372:in `run'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:2886:in `block in CompileOrStripBitcodeInBundle'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:2825:in `each'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:2825:in `CompileOrStripBitcodeInBundle'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:3112:in `block in ProcessIPA'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:3073:in `each'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:3073:in `ProcessIPA'
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/ipatool:4035:in `<main>'}
** EXPORT FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 70

**Comment by MikePendo** [comment]
@shariq-muhammad 
I forgot to ask what Pendo SDK version do u use, could u please try to update to latest one. (if you are using and old Pendo version that might be the case as fat frameworks will have have issues)
As far as I understand the issue happens only in AppCenter portal.  We have couple of clients that are using AppCenter but nobody reported an issue yet.
If we dont find a resolution on our side I would suggest to open and issue in [Appcenter](https://github.com/microsoft/appcenter/issues)
and see what can they suggest

**Comment by MikePendo** [comment]
@shariq-muhammad 
Any update about your issue?

**Comment by shariq-muhammad** [comment]
@MikePendo We are using `rn-pendo-sdk` version `^2.18.0`. The issue still persist at our end, please let us know if you have a resolution.

**Comment by MikePendo** [comment]
@shariq-muhammad 
As it works fine locally on both ends, its very hard to say why its not working in the app center. (without full logs )
They have a similar issue: [here](https://github.com/microsoft/appcenter/issues/1055)
I would suggest to ask their support: [AppCenter](https://github.com/microsoft/appcenter/issues/new/choose)

**Comment by shariq-muhammad** [comment]
@MikePendo Does having 'Enable BitCode' setting to 'yes' matters for Pendo for React Native? I saw it [here](https://cocoapods.org/pods/Insert), not sure if it is applicable in our case or not.

**Comment by MikePendo** [comment]
We release the SDK with Bitcode enabled. _Insert_ is a v1 and is no longer supported.
You can try to set it BUT again I need more detailed logs to help, and (in your case) I would try to see if the release process of Apple work for u i.e archive and upload, if it does it means that u r doing(or AppCenter) something additional in the release process if it doesnt work we will need to create sample RN project on our end and try to see if we have the same issue

**Comment by MikePendo** [comment]
So I have have created new app added Pendo and distributed it locally  as .ipa  (compiling with bitcode)
That worked for me. Can u do it locally on your Mac?

**Comment by MikePendo** [comment]
@shariq-muhammad 
Lets try to disable bitcode (and see if that helps)

**Comment by shariq-muhammad** [comment]
@MikePendo Yes, after disabling bitcode it did build without the errors.

**Comment by MikePendo** [comment]
In general I dont like those solution, coz those solution comes from some old threads to solve some issues on specific versions of Xcode. The _bitcode enabled_ has his purpose. I would suggest to upgrade to the latest version of Xcode and see if that works for u (if u have the time).
@shariq-muhammad I am closing the issue

**Comment by Rananjaya** [comment]
I have this issue when Distribute my app to TestFlight - Invalid Executable. The executable 'eText.app/Frameworks/Pendo.framework/Pendo' contains bitcode. (ID: e915c61d-bf47-4e02-a01c-faedaf31420a)

anyone know the solution for this...
