### ISSUE TITLE
React native sdk upgrade to 2.19

### ISSUE THREAD

**Issue by kristinadarroch** [pendo-io/pendo-mobile-ios#23]
Whenever I upgrade (to 2.19.0 from 2.180.0) I go through all the steps and I keep getting this error.

I go through all the steps and still run into it, I even got another coworker to try it on his end and he is still getting the same error. (this error is after a pod install)

error: Error: Unable to resolve module react/jsx-runtime from /Users/kdarroch/frontend/VisionNxMobile/node_modules/rn-pendo-sdk/lib/pendoRN.js: react/jsx-runtime could not be found within the project or in these directories:

  node_modules/rn-pendo-sdk/node_modules

  node_modules

  ../node_modules

If you are sure the module exists, try these steps:

 1. Clear watchman watches: watchman watch-del-all

 2. Delete node_modules and run yarn install

 3. Reset Metro's cache: yarn start --reset-cache

 4. Remove the cache: rm -rf /tmp/metro-*

**Comment by MikePendo** [comment]
```
npx react-native init SampleAppClean
yarn add rn-pendo-sdk
cd ios
pod install --repo-update
```
importing the following `import {withPendoRN, PendoSDK, NavigationLibraryType} from "rn-pendo-sdk";` in App.js
Running the app in Xcode (14.0.1) simulator , running as expected.
Maybe delete the node_module and install again.
If nothing else helps please share sample project I will have a look what might the issue

**Comment by kristinadarroch** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/22300685/204893232-e525fb02-cf58-4322-86b4-667fb6613c6e.png">
i am seeing the node modules for this, i have deleted node modules several times and tried to rebuild and still getting the same error

**Comment by MikePendo** [comment]
is it an expo project?

**Comment by kristinadarroch** [comment]
it is not an expo project

**Comment by MikePendo** [comment]
if u remove the import of Pendo does it compiles?

**Comment by kristinadarroch** [comment]
we were running into no issues, on 2.18 - i removed all references to pendo in our app and am getting the same error. I have tried all the above steps

**Comment by MikePendo** [comment]
I am not sure if u remove all the reference to pendo u still see the same error that it cant resolve pendo?

**Comment by kristinadarroch** [comment]
i kept it in my node modules and have the pod changes only, i'm not initializing the library or anything and i'm still getting the error

**Comment by MikePendo** [comment]
if u remove pendo totally will it compile ?
Do u run it from terminal or Xcode ? (can u try both ways)
When u delete all the cache did u kill the Metro, delete the app reset all the caches? (by killing the terminal)
if u create a new project like I did and add pendo will u be able to run it?

**Comment by MikePendo** [comment]
@kristinadarroch 
Did u manage to resolve the issue?

**Comment by MikePendo** [comment]
@kristinadarroch 
I am closing the issue feel free to open

**Comment by kristinadarroch** [comment]
Can you try on react native version 0.66.3, sorry was OOO

**Comment by MikePendo** [comment]
if u try the following [from here](https://github.com/pendo-io/pendo-mobile-ios/issues/23#issuecomment-1332433672) with RN 66 will it work for u?

**Comment by kristinadarroch** [comment]
@MikePendo yes I did follow from here, I think it might be the version of rn 66

**Comment by MikePendo** [comment]
@kristinadarroch 
```
npx react-native init SampleAppClean --version 0.66.3
yarn add rn-pendo-sdk
cd ios
pod install --repo-update

```
importing the following import {withPendoRN, PendoSDK, NavigationLibraryType} from "rn-pendo-sdk"; in App.js
Running the app in Xcode (14.0.1) simulator , running as expected.

As a last resort I would suggest t share with me some sample project with the issue and I will look into it
