### ISSUE TITLE
How to configure on AppDelegate.swift file

### ISSUE THREAD

**Issue by khayargoli** [pendo-io/pendo-mobile-ios#26]
Hello Pendo team,

So I was going to configure PENDO for flutter ios and I am following this tutorial: https://support.pendo.io/hc/en-us/articles/4405680165019-Developer-s-Guide-To-Installing-The-Pendo-Flutter-SDK#pendo-setup-and-initialization-0-3

Here in my project's AppDelegate.swift file I find this content already present, so how will be configuring it like described in the above tutorial? Will I be copy pasting the function in the guide in here or merge it in some way?

Please Help me, thanks a  lot.

```
import UIKit
import Flutter
import Pendo

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
     application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

}
```

**Comment by MikePendo** [comment]
The only thing u need to have in the `Appdelegate` is the open url method (and Pendo import).
I would suggest to look in the GitHub docs [here](https://github.com/pendo-io/pendo-mobile-ios/blob/master/pnddocs/flutter.md) I think its more clear

**Comment by MikePendo** [comment]
@khayargoli 
I am closing the issue, feel free to open it or asking
