### ISSUE TITLE
Pendo guide conflicting with iOS notification permission dialogue

### ISSUE THREAD

**Issue by shreyashah0** [pendo-io/pendo-mobile-ios#27]
Hi Pendo team, 

We have recently encountered an issue with Pendo guides conflicting with iOS notification permission dialogue box and failing to load the guide as result.

We tried to add a workaround, where we wait for notification permission result, before we trigger event and load pendo guide but that hasn't worked. We'd love to discuss any other solutions you may have tried that could help us fix this issue.
At the moment, we can only load the guide when the user disables notifications for the app from iOS settings. This won't work for any of our new users and the purpose of our guide is onboarding.

We would also like to know the timeline for Pendo to create a fix for this. Ideally, Pendo should be able to detect native OS dialogues and wait from them instead of conflicting this way.

**Comment by MikePendo** [comment]
Hi @shreyashah0 
Have you looked at this answer: https://github.com/pendo-io/pendo-mobile-ios/issues/7#issuecomment-1110194800
If you need the guide at specific place as a work around you can use _track event_ activation and trigger the guide after the user dismisses the Notification pop out.
(Pendo load all the guides on startSession call, basically if you you show the notification dialogue immediately after user log in to the app u could call the startSession immediately after the dialogue was dismissed)
See if any of the proposed workarounds work for you.
If not please open feature request

**Comment by MikePendo** [comment]
@shreyashah0 
I am closing the issue for now.
