### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [pendo-io/pendo-mobile-ios#28]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Pendo source plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Pendo APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

I know it's not an official project so if this is something interesting we would love to help sponsor both the Go SDK and the CloudQuery source plugin development. 

Best,
Yevgeny

**Comment by MikePendo** [comment]
Hi @yevgenypats 
Really sorry about the late response as I am not sure who would be the most relevant person to contact in that case.
@udilevin maybe u can advise?

**Comment by MikePendo** [comment]
or maybe just contact our support and ask for a quick call with our PM on mobile

**Comment by MikePendo** [comment]
@yevgenypats I hope u managed to contact one of our PM. I am closing the issue
