### ISSUE TITLE
Guide on App Launch won't trigger if user grants notifications

### ISSUE THREAD

**Issue by yago1994** [pendo-io/pendo-mobile-ios#7]
We have an app were we are using Pendo to display a Guide to new users upon App Launch. 

The guide doesn't show up properly on App Launch if the request for notifications from the user is granted, but it does if the request is denied. If the request is approved, the guide will show up at a random time through the app's use. 

Tested on iOS 15+, iPhone XR and higher

**Comment by MikePendo** [comment]
@yago1994 
Which SDK version are you using? please make sure u use the latest one.
Which platform you r targeting Native/RN/RNN/Xamarin/Flutter?

**Comment by yago1994** [comment]
Using 2.14.0 installed through Swift Package Manager
Targeting Native iOS

**Comment by yago1994** [comment]
Can confirm the issue is still present in 2.15.0

**Comment by MikePendo** [comment]
ok, After second thought I think I know what happening.
When u ask for notification permission IOS put your app in `UIApplicationStateInactive`
By default Pendo will show the guides _only_ when the app is in `UIApplicationStateActive` . (It doesnt make sense to show guides if the user doesnt interact with the app). As you try to display the app launch guide when the app in not active state the guide wont be displayed
and the app launch guide get stuck ..... and waits for the trigger, while in general there should be nothing to stop the app launch guide from being displayed(kind of interesting case I would say.)
Will the following work around can work for you:
Can u set up the guide for a specific page? (for the exact page that u want)
In that case for the first time when the user get asked for notifications the guide wont be displayed next time when the user see that page the guide will be displayed

**Comment by yago1994** [comment]
Got it, that makes sense.
I don't think we can set up the guide on a specific page because we are using it as a splash screen, so it needs to trigger on first launch. (Tried setting it up on page view rather than launch with the same set up but the trigger doesn't occur).
I could move the notification request to a different place in the app to avoid moving the guide.

**Comment by MikePendo** [comment]
@yago1994 
if u set up the guide on a specific page u should see it. In case you are triggering the notification permission on the same page, the guide will be blocked  when the notification pop up shows up BUT as son as u enter this page again the guide will show up. 
As thumb rule if _activation is page view_ the guide display trigger should always happen when the page appears.
Another work around (as u have suggested) is to  trigger the notification permission after you show the guide. (but I think in that case the notification pop up will appear on top of the guide as IOS will take advantage here)

**Comment by MikePendo** [comment]
@yago1994 
I am closing this issue, feel free to contact us
