### ISSUE TITLE
How to install the latest version?

### ISSUE THREAD

**Issue by Max-Job** [pendo-io/pendo-mobile-ios#8]
I tried to install Pendo:
```
platform :ios, '10.0'
pod 'Pendo'
```

As a result, was installed it:
> Installing Pendo (2.15.0.5328)

However, the latest version is 2.15.2.5470. How to install it?

Thank you

**Comment by MikePendo** [comment]
@Max-Job 
Sorry for late response. Can u please try 
`pod update Pendo`

**Comment by Max-Job** [comment]
> @Max-Job Sorry for late response. Can u please try `pod update Pendo`

Great! Thank you
I thought pod install was enough to install the latest dependencies.

**Comment by MikePendo** [comment]
yea they are easy to confuse but they r not the same:
[pod install vs pod update](https://guides.cocoapods.org/using/pod-install-vs-update.html)

**Comment by Max-Job** [comment]
> yea they are easy to confuse but they r not the same: [pod install vs pod update](https://guides.cocoapods.org/using/pod-install-vs-update.html)

thx
